### ISSUE TITLE
migration fail if founder list is long...as in migration-params.json example

### ISSUE THREAD

**Issue by orenyodfat** [daostack/migration#90]
ℹ 0x1f9706f8f653ea47c9a5a4aa2de369f7e48923a22ac18b2b121525aaa6f6629a | 0.00033 ETH | Minted 1000 reputation to 0x90f8bf6a479f320ead074411a4b0e7944ea8c9c1
ℹ 0x12484a1b772f647c7977a7d44e7a00ca469d09f5b8ba073df0e9fb33ce98b1d8 | 0.00018 ETH | Minted 1000 tokens to 0x90f8bf6a479f320ead074411a4b0e7944ea8c9c1
ℹ 0xa731d46ded6e9319d722c924bd4816263af83aa0420fb44895f60356a36afc9e | 0.00026 ETH | Minted 1000 reputation to 0xffcf8fdee72ac11b5c542428b35eef5769c409f0
ℹ 0x6640697f30bdcb3b9927f75df9e0de845cd566ebeae6685cea939cbe61d4844f | 0.00018 ETH | Minted 1000 tokens to 0xffcf8fdee72ac11b5c542428b35eef5769c409f0
ℹ 0xa89e74df66ec0cde7de57e8fb0cc799d3c3f76b2febb13e451120e23d0e4a661 | 0.00026 ETH | Minted 1000 reputation to 0x22d491bde2303f2f43325b2108d26f1eaba1e32b
ℹ 0xa5ce58a0cd2db6c74c71476561e1469b31ea751bf620aa56f20aa8897f9e8bf5 | 0.00018 ETH | Minted 1000 tokens to 0x22d491bde2303f2f43325b2108d26f1eaba1e32b
ℹ 0x797fee150a8ee843fa6ec654bd88de239cfad488a7ee4790f707b453a8de3b50 | 0.00026 ETH | Minted 1000 reputation to 0xe11ba2b4d45eaed5996cd0823791e0c93114882d
ℹ 0xbd0e896dad4797505e905c0d932010251e10afce5452e1d4e3fe9b44121880d8 | 0.00018 ETH | Minted 1000 tokens to 0xe11ba2b4d45eaed5996cd0823791e0c93114882d
ℹ 0x9f275a4602e878861949f3af15c270d643ade30c911f777b4595b7cab2ee65af | 0.00026 ETH | Minted 1000 reputation to 0xd03ea8624c8c5987235048901fb614fdca89b117
ℹ 0x4ab575fe7d1cbffe9d667c044cf7de295837f1fdbdc4663d954a256e46d70ab2 | 0.00018 ETH | Minted 1000 tokens to 0xd03ea8624c8c5987235048901fb614fdca89b117
ℹ 0xe233620c0b027d1af221fda374ac64e46c390e5d963f9a420b690ec87e53eba7 | 0.00026 ETH | Minted 1000 reputation to 0x95ced938f7991cd0dfcb48f0a06a40fa1af46ebc
ℹ 0xac0602516ee53c7bff3bb243ff3cc0e3bc0bb7f28dabb81bb4fdfcb64288f995 | 0.00018 ETH | Minted 1000 tokens to 0x95ced938f7991cd0dfcb48f0a06a40fa1af46ebc
ℹ 0x014c19bbafafff9de7af3dd989856d8872e5872d5966303088f43f399a8058cb | 0.00015 ETH | Finished transferring Avatar to Controller ownership
⠼ Transfer Reputation to Controller ownershipError: Returned error: Transaction nonce is too low. Try incrementing the nonce.
    at Object.ErrorResponse (/Users/oren/.npm-global/lib/node_modules/@daostack/migration/node_modules/web3-core-helpers/src/errors.js:29:16)
    at /Users/oren/.npm-global/lib/node_modules/@daostack/migration/node_modules/web3-core-requestmanager/src/index.js:140:36
    at XMLHttpRequest.request.onreadystatechange (/Users/oren/.npm-global/lib/node_modules/@daostack/migration/node_modules/web3-providers-http/src/index.js:96:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/oren/.npm-global/lib/node_modules/@daostack/migration/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/Users/oren/.npm-global/lib/node_modules/@daostack/migration/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (/Users/oren/.npm-global/lib/node_modules/@daostack/migration/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (/Users/oren/.npm-global/lib/node_modules/@daostack/migration/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by ben-kaufman** [comment]
This doesn't seem related to the length of the list. On which network did you try it?

**Comment by orenyodfat** [comment]
kovan
